//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServerManager.ServiceReferenceFiliale {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Filiale", Namespace="http://schemas.datacontract.org/2004/07/WCFServerDB")]
    [System.SerializableAttribute()]
    public partial class Filiale : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CAPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cittaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idFilialeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string indirizzoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroDiTelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string provinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CAP {
            get {
                return this.CAPField;
            }
            set {
                if ((this.CAPField.Equals(value) != true)) {
                    this.CAPField = value;
                    this.RaisePropertyChanged("CAP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string citta {
            get {
                return this.cittaField;
            }
            set {
                if ((object.ReferenceEquals(this.cittaField, value) != true)) {
                    this.cittaField = value;
                    this.RaisePropertyChanged("citta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idFiliale {
            get {
                return this.idFilialeField;
            }
            set {
                if ((object.ReferenceEquals(this.idFilialeField, value) != true)) {
                    this.idFilialeField = value;
                    this.RaisePropertyChanged("idFiliale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string indirizzo {
            get {
                return this.indirizzoField;
            }
            set {
                if ((object.ReferenceEquals(this.indirizzoField, value) != true)) {
                    this.indirizzoField = value;
                    this.RaisePropertyChanged("indirizzo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroDiTelefono {
            get {
                return this.numeroDiTelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroDiTelefonoField, value) != true)) {
                    this.numeroDiTelefonoField = value;
                    this.RaisePropertyChanged("numeroDiTelefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string provincia {
            get {
                return this.provinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.provinciaField, value) != true)) {
                    this.provinciaField = value;
                    this.RaisePropertyChanged("provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stato {
            get {
                return this.statoField;
            }
            set {
                if ((object.ReferenceEquals(this.statoField, value) != true)) {
                    this.statoField = value;
                    this.RaisePropertyChanged("stato");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceFiliale.IServiceFiliale")]
    public interface IServiceFiliale {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFiliale/GetFiliale", ReplyAction="http://tempuri.org/IServiceFiliale/GetFilialeResponse")]
        WCFServerManager.ServiceReferenceFiliale.Filiale GetFiliale(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFiliale/GetFiliale", ReplyAction="http://tempuri.org/IServiceFiliale/GetFilialeResponse")]
        System.Threading.Tasks.Task<WCFServerManager.ServiceReferenceFiliale.Filiale> GetFilialeAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFiliale/ModificaDatiFiliale", ReplyAction="http://tempuri.org/IServiceFiliale/ModificaDatiFilialeResponse")]
        bool ModificaDatiFiliale(string idFiliale, WCFServerManager.ServiceReferenceFiliale.Filiale nuovaFiliale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFiliale/ModificaDatiFiliale", ReplyAction="http://tempuri.org/IServiceFiliale/ModificaDatiFilialeResponse")]
        System.Threading.Tasks.Task<bool> ModificaDatiFilialeAsync(string idFiliale, WCFServerManager.ServiceReferenceFiliale.Filiale nuovaFiliale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFiliale/GetNameFiliale", ReplyAction="http://tempuri.org/IServiceFiliale/GetNameFilialeResponse")]
        string GetNameFiliale(string idFiliale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFiliale/GetNameFiliale", ReplyAction="http://tempuri.org/IServiceFiliale/GetNameFilialeResponse")]
        System.Threading.Tasks.Task<string> GetNameFilialeAsync(string idFiliale);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceFilialeChannel : WCFServerManager.ServiceReferenceFiliale.IServiceFiliale, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceFilialeClient : System.ServiceModel.ClientBase<WCFServerManager.ServiceReferenceFiliale.IServiceFiliale>, WCFServerManager.ServiceReferenceFiliale.IServiceFiliale {
        
        public ServiceFilialeClient() {
        }
        
        public ServiceFilialeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceFilialeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceFilialeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceFilialeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFServerManager.ServiceReferenceFiliale.Filiale GetFiliale(string username) {
            return base.Channel.GetFiliale(username);
        }
        
        public System.Threading.Tasks.Task<WCFServerManager.ServiceReferenceFiliale.Filiale> GetFilialeAsync(string username) {
            return base.Channel.GetFilialeAsync(username);
        }
        
        public bool ModificaDatiFiliale(string idFiliale, WCFServerManager.ServiceReferenceFiliale.Filiale nuovaFiliale) {
            return base.Channel.ModificaDatiFiliale(idFiliale, nuovaFiliale);
        }
        
        public System.Threading.Tasks.Task<bool> ModificaDatiFilialeAsync(string idFiliale, WCFServerManager.ServiceReferenceFiliale.Filiale nuovaFiliale) {
            return base.Channel.ModificaDatiFilialeAsync(idFiliale, nuovaFiliale);
        }
        
        public string GetNameFiliale(string idFiliale) {
            return base.Channel.GetNameFiliale(idFiliale);
        }
        
        public System.Threading.Tasks.Task<string> GetNameFilialeAsync(string idFiliale) {
            return base.Channel.GetNameFilialeAsync(idFiliale);
        }
    }
}
